# Goal [behavior]: name of the behavior to be executed
# Result [noErrors]: true if behavior finished executing correctly, false otherwise
# Feedback: none as NaoQI API cannot be queried in this respect
string behavior
---
bool noErrors
---
